# Generated by Django 5.2.5 on 2025-09-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedfile_report_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_column', models.CharField(max_length=255)),
                ('problem_type', models.CharField(choices=[('REGRESSION', 'Regression'), ('CLASSIFICATION', 'Classification')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('test_size', models.FloatField(default=0.2)),
                ('random_state', models.IntegerField(default=42)),
                ('preprocessing_info', models.JSONField(blank=True, null=True)),
                ('model_results', models.JSONField(blank=True, null=True)),
                ('model_paths', models.JSONField(blank=True, null=True)),
                ('plot_paths', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('best_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('best_model_score', models.FloatField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
